### ISSUE TITLE
Plugin not working on all configurations

### ISSUE THREAD

**Issue by MyWay** [LouisT/KiwiIRC-Emoji-Twemoji#1]
Some user is reporting issues after I have added this plugin to my kiwi installation. They can't see what other users type anymore and they do have some other issue.
It seems they're all using Google Chrome (last available version), but I was not able to reproduce it, unfortunately.
You can see all the issues in the screenshot and check differences connecting to http://www.echatta.net/client

![immagine1-2](https://cloud.githubusercontent.com/assets/1765284/13862087/46736774-ec91-11e5-95ef-8e7df1576d2a.jpg)

**Comment by LouisT** [comment]
I can't replicate the issue either. I need more information such as if they're using a vanilla install of Chrome (no plugins) and if they are which ones, as well as the exact version they're using.

**Comment by MyWay** [comment]
It seems it happens if you have Avira installed with its Google chrome extension. Can you do something about it?

**Comment by LouisT** [comment]
Avira as in the Antivirus for windows/mac? If so, I run Linux so it might take some time to figure out how to fix this. I assume it has to do with the program blocking the CDN. Maybe try running it as a local install?

**Comment by LouisT** [comment]
Ok, so I installed Avira and it's chrome extension on a Windows laptop I have laying around. As I predicted, it is blocking MaxCDN as a "tracker". If you open the browser extension to view the list of blocked trackers you can unblock it by clicking the "unblock" toggle. Here is what it looks like:

![avira](https://cloud.githubusercontent.com/assets/860621/14054006/d69b39b0-f292-11e5-99fa-a929e8135132.png)

Since this is a client side chrome extension there is nothing I can do besides suggest running the plugin generator as a local install instead of using the CDN.

**Comment by MyWay** [comment]
I will run it locally, not a problem, thank you very much.
